# Generated by Django 4.0.6 on 2023-08-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezangofilemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=255),
        ),
    ]
